resource: 'google_privileged_access_manager_settings'
generation_type: 'mmv1'
source_file: 'products/privilegedaccessmanager/Settings.yaml'
api_service_name: 'privilegedaccessmanager.googleapis.com'
api_version: 'v1beta'
api_resource_type_kind: 'Settings'
api_variant_patterns:
  - 'folders/{folder}/locations/{location}/settings'
  - 'organizations/{organization}/locations/{location}/settings'
  - 'projects/{project}/locations/{location}/settings'
fields:
  - api_field: 'createTime'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.adminNotifications.grantActivated'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.adminNotifications.grantActivationFailed'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.adminNotifications.grantEnded'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.adminNotifications.grantExternallyModified'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.approverNotifications.pendingApproval'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.requesterNotifications.entitlementAssigned'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.requesterNotifications.grantActivated'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.requesterNotifications.grantActivationFailed'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.requesterNotifications.grantDenied'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.requesterNotifications.grantEnded'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.requesterNotifications.grantExpired'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.requesterNotifications.grantExternallyModified'
  - api_field: 'emailNotificationSettings.customNotificationBehavior.requesterNotifications.grantRevoked'
  - api_field: 'emailNotificationSettings.disableAllNotifications'
  - api_field: 'etag'
  - field: 'location'
    provider_only: true
  - api_field: 'name'
  - field: 'parent'
    provider_only: true
  - api_field: 'serviceAccountApproverSettings.enabled'
  - api_field: 'updateTime'
